//auth
export const AUTH = "AUTH"
export const LOGOUT = "LOGOUT"

//errors
export const GET_MESSAGES = "GET_MESSAGES"
export const CLEAR_MESSAGES = "CLEAR_MESSAGES"
export const FETCH_USER = "FETCH_USER"

//categories
export const ADD_CATEGORY = "ADD_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"

//subCategories
export const ADD_SUBCATEGORY = "ADD_SUBCATEGORY"
export const REMOVE_SUBCATEGORY = "REMOVE_SUBCATEGORY"
export const FETCH_SUBCATEGORIES = "FETCH_SUBCATEGORIES"
export const ADD_TO_SUBCATEGORY = "ADD_TO_SUBCATEGORY"
export const REMOVE_FROM_SUBCATEGORY = "REMOVE_FROM_SUBCATEGORY"

//products
export const FETCH_PRODUCTS = "FETCH_PRODUCTS"
export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const UPDATE_PRODUCT = "UPDATE_PRODUCT"
export const LIKE_PRODUCT = "LIKE_PRODUCT"
export const EDIT_PRODUCT = "EDIT_PRODUCT"
